### PR TITLE
Add Object#require! that downloads and activates a missing gem

### PR DESCRIPTION
**Pull request by ridiculous**

### CODE REVIEW

**Comment by kawikak** [comment]
Yea why not. I'll have to try it with rbenv and gem sets to see if I don't confuse myself as to where the Gem ends up

**Comment by ridiculous** [comment]
I've noticed it doesn't breaks with gems that have to "build native extensions" such as nokogiri... so not perfect. But kind of a nice way to play with gems without having to leave your console and add em to the Gemfile.

**Comment by ridiculous** [comment]
Feel free to merge if you want. I just pushed one more commit i had laying around

**Comment by ridiculous** [comment]
but yeah, let me know if it works with rbenv

**Pull request merged**
